const TYPES={core:{name:"CORE",icon:"◆",color:"#35c9ff",hp:180,cost:0,power:1},armor:{name:"ARMOR",icon:"▣",color:"#718096",hp:130,cost:10,power:0},gun:{name:"CANNON",icon:"➤",color:"#ffb020",hp:65,cost:25,power:3,rate:520,dmg:3,spd:9},rapid:{name:"MINIGUN",icon:"≡",color:"#ff7a45",hp:55,cost:45,power:5,rate:150,dmg:1,spd:11},rocket:{name:"ROCKET",icon:"✦",color:"#e85dff",hp:55,cost:70,power:8,rate:1000,dmg:9,spd:6,blast:55},wheel:{name:"TRACK",icon:"●",color:"#35d07f",hp:80,cost:12,power:0},shield:{name:"SHIELD",icon:"⬡",color:"#7c8cff",hp:70,cost:60,power:2},repair:{name:"REPAIR",icon:"✚",color:"#44e0c1",hp:55,cost:80,power:2}};
const c=document.querySelector("#game"),x=c.getContext("2d"),A=document.querySelector("#arena"),Q=s=>document.querySelector(s);let W=0,H=0,D=1,S=36,selected="core",parts=[],coins=150,gems=0,level=1,battle=false,enemies=[],shots=[],particles=[],wave=1,last=0,spawn=0,tank={x:0,y:0,a:0,vx:0,vy:0},joy={on:false,id:0,sx:0,sy:0,x:0,y:0};
function resize(){let r=A.getBoundingClientRect();D=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;c.width=W*D;c.height=H*D;x.setTransform(D,0,0,D,0,0);if(!tank.x){tank.x=W/2;tank.y=H/2}}addEventListener("resize",resize);setTimeout(resize,0);
function ui(){Q("#coins").textContent=Math.floor(coins);Q("#gems").textContent=gems;Q("#level").textContent=level;Q("#partCount").textContent=parts.length;Q("#power").textContent=parts.reduce((n,p)=>n+TYPES[p.type].power,0);let core=parts.find(p=>p.type==="core");Q("#hpText").textContent=core?Math.ceil(core.hp):0}
function tabs(id){["build","shop","levels"].forEach(n=>{Q("#"+n+"Screen").classList.toggle("activeScreen",n===id);Q("#"+n+"Tab").classList.toggle("active",n===id)});setTimeout(resize,0)}Q("#buildTab").onclick=()=>tabs("build");Q("#shopTab").onclick=()=>tabs("shop");Q("#levelsTab").onclick=()=>tabs("levels");Q("#playLevel").onclick=()=>{tabs("build");startBattle()};
function makeButtons(root){for(let [k,t] of Object.entries(TYPES)){let b=document.createElement("button");b.dataset.part=k;b.innerHTML="<strong>"+t.icon+"</strong>"+t.name+"<i>"+(t.cost||"FREE")+"</i>";b.onclick=()=>{selected=k;document.querySelectorAll("[data-part]").forEach(z=>z.classList.toggle("selected",z.dataset.part===k));tabs("build")};root.appendChild(b)}}makeButtons(Q("#shop"));makeButtons(Q("#quickbar"));document.querySelectorAll('[data-part="core"]').forEach(b=>b.classList.add("selected"));
function world(p){let ca=Math.cos(tank.a),sa=Math.sin(tank.a),lx=p.gx*S,ly=p.gy*S;return{x:tank.x+lx*ca-ly*sa,y:tank.y+lx*sa+ly*ca}}function connected(gx,gy){return parts.length===0||parts.some(p=>Math.abs(p.gx-gx)+Math.abs(p.gy-gy)===1)}
let holdTimer=null,downPart=null;c.addEventListener("pointerdown",e=>{let r=c.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top;if(battle){joy={on:true,id:e.pointerId,sx:px,sy:py,x:px,y:py};Q("#joystick").hidden=false;Q("#joystick").style.left=px-46+"px";Q("#joystick").style.top=py-46+"px";c.setPointerCapture(e.pointerId);return}let gx=Math.round((px-W/2)/S),gy=Math.round((py-H/2)/S),old=parts.find(p=>p.gx===gx&&p.gy===gy);downPart=old;if(old){holdTimer=setTimeout(()=>{parts=parts.filter(p=>p!==old);coins+=Math.floor(TYPES[old.type].cost*.75);downPart=null;ui()},550);return}if(selected==="core"&&parts.some(p=>p.type==="core"))return;if(!connected(gx,gy)||Math.abs(gx)>6||Math.abs(gy)>6)return;let t=TYPES[selected];if(coins<t.cost)return;coins-=t.cost;parts.push({gx,gy,type:selected,hp:t.hp,rot:0,cool:0});ui()});
c.addEventListener("pointerup",e=>{clearTimeout(holdTimer);if(!battle&&downPart){downPart.rot=(downPart.rot+1)%4;downPart=null}if(e.pointerId===joy.id){joy.on=false;Q("#joystick").hidden=true;Q("#joystick div").style.transform=""}});c.addEventListener("pointercancel",()=>clearTimeout(holdTimer));c.addEventListener("pointermove",e=>{if(!joy.on||e.pointerId!==joy.id)return;let r=c.getBoundingClientRect();joy.x=e.clientX-r.left;joy.y=e.clientY-r.top;let dx=joy.x-joy.sx,dy=joy.y-joy.sy,d=Math.hypot(dx,dy)||1,m=Math.min(32,d);Q("#joystick div").style.transform="translate("+dx/d*m+"px,"+dy/d*m+"px)"});
Q("#reset").onclick=()=>{if(battle)return;parts.forEach(p=>coins+=Math.floor(TYPES[p.type].cost*.75));parts=[];ui()};Q("#battle").onclick=startBattle;
function startBattle(){if(battle){battle=false;Q("#battle").textContent="FIGHT";Q("#message").textContent="BUILD YOUR MACHINE";return}if(!parts.some(p=>p.type==="core")||!parts.some(p=>["gun","rapid","rocket"].includes(p.type)))return;parts.forEach(p=>p.hp=TYPES[p.type].hp);battle=true;enemies=[];shots=[];wave=1;tank.x=W/2;tank.y=H/2;tank.a=0;tank.vx=tank.vy=0;Q("#battle").textContent="RETREAT";Q("#message").textContent="THE SCRAPS - WAVE 1"}
function nearest(px,py){let b=null,bd=1e9;for(let e of enemies){let d=(e.x-px)**2+(e.y-py)**2;if(d<bd){bd=d;b=e}}return b}function burst(px,py,col,n=8){for(let i=0;i<n;i++){let a=Math.random()*6.28,s=Math.random()*2.5;particles.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:30,col})}}
function enemy(){let side=Math.floor(Math.random()*4),p=side<2?{x:Math.random()*W,y:side?H+20:-20}:{x:side===2?-20:W+20,y:Math.random()*H},hp=3+Math.floor(wave*.7);enemies.push({...p,hp,max:hp,r:12,spd:.7+wave*.025})}
function update(dt){if(!battle)return;spawn-=dt;if(spawn<=0){enemy();spawn=Math.max(18,55-wave*2)}let dx=joy.x-joy.sx,dy=joy.y-joy.sy,d=Math.hypot(dx,dy)||1,p=joy.on?Math.min(d/65,1):0;if(joy.on&&p>.05){let target=Math.atan2(dy,dx),dif=Math.atan2(Math.sin(target-tank.a),Math.cos(target-tank.a));tank.a+=dif*Math.min(1,.22*dt);let sp=(1.25+parts.filter(q=>q.type==="wheel").length*.12)*p;tank.vx+=(Math.cos(tank.a)*sp-tank.vx)*.12*dt;tank.vy+=(Math.sin(tank.a)*sp-tank.vy)*.12*dt}else{tank.vx*=Math.pow(.86,dt);tank.vy*=Math.pow(.86,dt)}tank.x=Math.max(55,Math.min(W-55,tank.x+tank.vx*dt));tank.y=Math.max(55,Math.min(H-55,tank.y+tank.vy*dt));
for(let p of parts){if(!["gun","rapid","rocket"].includes(p.type)||p.hp<=0)continue;p.cool-=dt;let q=world(p),e=nearest(q.x,q.y),t=TYPES[p.type];if(e&&p.cool<=0){let a=Math.atan2(e.y-q.y,e.x-q.x);shots.push({x:q.x,y:q.y,vx:Math.cos(a)*t.spd,vy:Math.sin(a)*t.spd,d:t.dmg,b:t.blast||0,l:100});p.cool=t.rate/16.67}}
for(let e of enemies){let a=Math.atan2(tank.y-e.y,tank.x-e.x);e.x+=Math.cos(a)*e.spd*dt;e.y+=Math.sin(a)*e.spd*dt;let hit=parts.map(p=>({p,q:world(p)})).filter(z=>z.p.hp>0).sort((a,b)=>Math.hypot(e.x-a.q.x,e.y-a.q.y)-Math.hypot(e.x-b.q.x,e.y-b.q.y))[0];if(hit&&Math.hypot(e.x-hit.q.x,e.y-hit.q.y)<28)hit.p.hp-=.16*dt}
for(let s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.l-=dt;for(let e of enemies)if(e.hp>0&&Math.hypot(s.x-e.x,s.y-e.y)<17){e.hp-=s.d;s.l=0;if(e.hp<=0){coins+=2;burst(e.x,e.y,"#ff6b58")};break}}shots=shots.filter(s=>s.l>0);enemies=enemies.filter(e=>e.hp>0);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.l-=dt});particles=particles.filter(p=>p.l>0);let core=parts.find(p=>p.type==="core");if(!core||core.hp<=0){battle=false;Q("#battle").textContent="FIGHT";Q("#message").textContent="BOSS DESTROYED"}ui()}
function rr(a,b,w,h,r){x.beginPath();x.roundRect(a,b,w,h,r);x.fill();x.stroke()}function part(p){if(p.hp<=0)return;let q=world(p),t=TYPES[p.type];x.save();x.translate(q.x,q.y);x.rotate(tank.a+p.rot*Math.PI/2);x.fillStyle=t.color;x.strokeStyle="#d8f2ff";x.lineWidth=1.5;if(p.type==="wheel"){x.fillStyle="#16222e";rr(-16,-12,32,24,5)}else{rr(-15,-15,30,30,4);if(["gun","rapid","rocket"].includes(p.type)){x.fillStyle="#e7f4ff";x.fillRect(8,-4,24,8)}if(p.type==="core"){x.fillStyle="#fff";x.beginPath();x.moveTo(0,-8);x.lineTo(8,0);x.lineTo(0,8);x.lineTo(-8,0);x.fill()}}x.restore()}
function draw(){x.clearRect(0,0,W,H);x.strokeStyle="#132334";for(let i=0;i<W;i+=S){x.beginPath();x.moveTo(i,0);x.lineTo(i,H);x.stroke()}for(let i=0;i<H;i+=S){x.beginPath();x.moveTo(0,i);x.lineTo(W,i);x.stroke()}if(!battle){tank.x=W/2;tank.y=H/2;tank.a=0}parts.forEach(part);for(let e of enemies){x.fillStyle="#e95151";x.beginPath();x.arc(e.x,e.y,e.r,0,7);x.fill();x.fillStyle="#ff5d75";x.fillRect(e.x-12,e.y-19,24*e.hp/e.max,3)}for(let s of shots){x.fillStyle=s.b?"#ffb020":"#eaf8ff";x.beginPath();x.arc(s.x,s.y,4,0,7);x.fill()}for(let p of particles){x.globalAlpha=p.l/30;x.fillStyle=p.col;x.fillRect(p.x,p.y,3,3)}x.globalAlpha=1}
function loop(t){let dt=Math.min((t-last)/16.67||1,2);last=t;update(dt);draw();requestAnimationFrame(loop)}ui();requestAnimationFrame(loop);