const c=document.querySelector("#game"),ctx=c.getContext("2d"),arena=document.querySelector("#arena"),Q=s=>document.querySelector(s);let W,H,D=1,selected="core",parts=[],coins=150,gems=0,level=1,battle=false,enemies=[],shots=[],particles=[],wave=0,score=0,last=0,spawnClock=0,waveLeft=0,tank={x:0,y:0,angle:0},joy={on:false,id:0,sx:0,sy:0,x:0,y:0};const S=34,T={core:{c:"#35c9ff",hp:180,cost:0},armor:{c:"#718096",hp:130,cost:10},gun:{c:"#ffb020",hp:65,cost:25,rate:520,dmg:3,spd:9},rapid:{c:"#ff7a45",hp:55,cost:45,rate:150,dmg:1,spd:11},rocket:{c:"#e85dff",hp:55,cost:70,rate:1050,dmg:9,spd:6,blast:55},wheel:{c:"#35d07f",hp:80,cost:12},shield:{c:"#7c8cff",hp:70,cost:60},repair:{c:"#44e0c1",hp:55,cost:80}};
function resize(){let r=arena.getBoundingClientRect();D=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;c.width=W*D;c.height=H*D;ctx.setTransform(D,0,0,D,0,0);if(!tank.x){tank.x=W/2;tank.y=H/2}}addEventListener("resize",resize);resize();
function ui(){Q("#coins").textContent=Math.floor(coins);Q("#gems").textContent=gems;Q("#level").textContent=level;Q("#wave").textContent=wave;Q("#score").textContent=score;let k=parts.find(p=>p.type==="core"),h=k?Math.max(0,Math.ceil(k.hp)):0,m=k?T.core.hp:100;Q("#hpText").textContent=h+"/"+m;Q("#hpBar").style.width=h/m*100+"%"}function msg(s){Q("#message").textContent=s}function pc(p){let ca=Math.cos(tank.angle),sa=Math.sin(tank.angle),lx=p.x*S,ly=p.y*S;return{x:tank.x+lx*ca-ly*sa,y:tank.y+lx*sa+ly*ca}}
document.querySelectorAll("#shop button").forEach(b=>b.onclick=()=>{selected=b.dataset.part;document.querySelectorAll("#shop button").forEach(q=>q.classList.toggle("selected",q===b));msg("Selected "+b.querySelector("small").textContent)});
function linked(x,y){return parts.length===0||parts.some(p=>Math.abs(p.x-x)+Math.abs(p.y-y)===1)}
c.addEventListener("pointerdown",e=>{let r=c.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top;if(battle){joy={on:true,id:e.pointerId,sx:px,sy:py,x:px,y:py};Q("#joystick").hidden=false;Q("#joystick").style.left=px-46+"px";Q("#joystick").style.top=py-46+"px";c.setPointerCapture(e.pointerId);return}let gx=Math.round((px-W/2)/S),gy=Math.round((py-H/2)/S);if(Math.abs(gx)>5||Math.abs(gy)>5)return;let old=parts.find(p=>p.x===gx&&p.y===gy);if(old){if(["gun","rapid","rocket"].includes(old.type)){old.rot=(old.rot+1)%4;msg("Weapon rotated")}else{parts=parts.filter(p=>p!==old);coins+=Math.floor(T[old.type].cost*.75)}ui();return}if(selected==="core"&&parts.some(p=>p.type==="core"))return msg("Only one CORE allowed");if(!linked(gx,gy))return msg("Connect new parts to the machine");let cost=T[selected].cost;if(coins<cost)return msg("Not enough coins");coins-=cost;parts.push({x:gx,y:gy,type:selected,hp:T[selected].hp,rot:0,cool:0});ui()});
c.addEventListener("pointermove",e=>{if(!joy.on||e.pointerId!==joy.id)return;let r=c.getBoundingClientRect();joy.x=e.clientX-r.left;joy.y=e.clientY-r.top;let dx=joy.x-joy.sx,dy=joy.y-joy.sy,d=Math.hypot(dx,dy)||1,m=Math.min(d,32);Q("#joystick div").style.transform="translate("+dx/d*m+"px,"+dy/d*m+"px)"});function joyEnd(e){if(e.pointerId!==joy.id)return;joy.on=false;Q("#joystick").hidden=true;Q("#joystick div").style.transform=""}c.addEventListener("pointerup",joyEnd);c.addEventListener("pointercancel",joyEnd);
Q("#clear").onclick=()=>{if(battle)return;parts.forEach(p=>coins+=Math.floor(T[p.type].cost*.75));parts=[];ui();msg("Build reset - 75% refunded")};Q("#battle").onclick=()=>battle?end(false):start();
function start(){if(!parts.some(p=>p.type==="core"))return msg("Place your CORE first");if(!parts.some(p=>["gun","rapid","rocket"].includes(p.type)))return msg("Add a weapon first");parts.forEach(p=>p.hp=T[p.type].hp);battle=true;enemies=[];shots=[];particles=[];wave=1;score=0;tank.x=W/2;tank.y=H/2;tank.angle=0;Q("#battle").textContent="RETREAT";Q("#mode").textContent="COMBAT";beginWave();ui()}function end(dead){battle=false;joy.on=false;Q("#joystick").hidden=true;Q("#battle").textContent="DEPLOY";Q("#mode").textContent="GARAGE";Q("#boss").hidden=true;enemies=[];shots=[];if(dead){let r=Math.floor(score/25);coins+=r;msg("CORE DESTROYED - salvage +"+r+" coins")}else msg("Returned to garage");ui()}
function beginWave(){let boss=wave%5===0;waveLeft=boss?1:5+wave*2;spawnClock=0;msg(boss?"BOSS WAVE "+wave:"WAVE "+wave);Q("#boss").hidden=!boss}
function spawn(){let boss=wave%5===0&&waveLeft===1,edge=Math.floor(Math.random()*4),p=edge<2?{x:Math.random()*W,y:edge?H+30:-30}:{x:edge===2?-30:W+30,y:Math.random()*H},hp=boss?45+wave*7:3+Math.floor(wave*.65);enemies.push({...p,hp,max:hp,speed:boss?.48:.75+Math.min(wave*.035,.65),r:boss?27:12,boss,hit:0});waveLeft--}
function nearest(x,y){let z=null,bd=1e12;for(let e of enemies){let d=(e.x-x)**2+(e.y-y)**2;if(d<bd){bd=d;z=e}}return z}function boom(x,y,col,n=8){for(let i=0;i<n;i++){let a=Math.random()*6.28,s=Math.random()*3+1;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:30+Math.random()*20,col})}}
function hit(e,d,b){if(!e||e.hp<=0)return;e.hp-=d;e.hit=4;if(b){for(let q of enemies)if(Math.hypot(q.x-e.x,q.y-e.y)<b)q.hp-=d*.45;boom(e.x,e.y,"#ffb020",16)}if(e.hp<=0){score+=e.boss?500:25;coins+=e.boss?60:2;if(e.boss){gems++;level++;boom(e.x,e.y,"#ef476f",30)}else boom(e.x,e.y,"#ff5d5d")}}
function update(dt){if(!battle)return;let dx=joy.x-joy.sx,dy=joy.y-joy.sy,d=Math.hypot(dx,dy)||1,pow=joy.on?Math.min(d/55,1):0,wheels=parts.filter(p=>p.type==="wheel"&&p.hp>0).length,maxSp=(1.05+wheels*.18)*pow;if(joy.on&&pow>.08){let desired=Math.atan2(dy,dx),diff=Math.atan2(Math.sin(desired-tank.angle),Math.cos(desired-tank.angle)),turn=(.045+wheels*.006)*dt;tank.angle+=Math.max(-turn,Math.min(turn,diff));let align=Math.max(.15,1-Math.abs(diff)/Math.PI);tank.x+=Math.cos(tank.angle)*maxSp*align*dt;tank.y+=Math.sin(tank.angle)*maxSp*align*dt}tank.x=Math.max(65,Math.min(W-65,tank.x));tank.y=Math.max(65,Math.min(H-65,tank.y));spawnClock-=16.67*dt;if(waveLeft>0&&spawnClock<=0){spawn();spawnClock=Math.max(250,780-wave*22)}if(waveLeft===0&&!enemies.length){wave++;beginWave()}
for(let p of parts){if(!["gun","rapid","rocket"].includes(p.type)||p.hp<=0)continue;p.cool-=16.67*dt;let a=pc(p),e=nearest(a.x,a.y);if(e&&p.cool<=0){let ang=Math.atan2(e.y-a.y,e.x-a.x),t=T[p.type];shots.push({x:a.x,y:a.y,vx:Math.cos(ang)*t.spd,vy:Math.sin(ang)*t.spd,d:t.dmg,b:t.blast||0,life:110});p.cool=t.rate}}
for(let e of enemies){let ang=Math.atan2(tank.y-e.y,tank.x-e.x);e.x+=Math.cos(ang)*e.speed*dt;e.y+=Math.sin(ang)*e.speed*dt;let target=null,td=1e9;for(let p of parts){if(p.hp<=0)continue;let a=pc(p),dd=Math.hypot(e.x-a.x,e.y-a.y);if(dd<td){td=dd;target=p}}if(target&&td<e.r+17){target.hp-=(e.boss?.35:.18)*dt;e.x-=Math.cos(ang)}}
for(let s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(let e of enemies)if(e.hp>0&&Math.hypot(s.x-e.x,s.y-e.y)<e.r+5){hit(e,s.d,s.b);s.life=0;break}}shots=shots.filter(s=>s.life>0&&s.x>-20&&s.y>-20&&s.x<W+20&&s.y<H+20);enemies=enemies.filter(e=>e.hp>0);let core=parts.find(p=>p.type==="core");if(parts.some(p=>p.type==="repair"&&p.hp>0)&&core)core.hp=Math.min(T.core.hp,core.hp+.025*dt);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;p.vx*=.98;p.vy*=.98});particles=particles.filter(p=>p.life>0);if(!core||core.hp<=0)return end(true);let boss=enemies.find(e=>e.boss);if(boss)Q("#bossBar").style.width=boss.hp/boss.max*100+"%";ui()}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();ctx.stroke()}function drawPart(p){if(p.hp<=0)return;let a=pc(p),t=T[p.type],ratio=p.hp/t.hp;ctx.save();ctx.translate(a.x,a.y);ctx.rotate(tank.angle+(p.rot||0)*Math.PI/2);ctx.fillStyle=t.c;ctx.strokeStyle="#d9efff";ctx.lineWidth=1.5;if(p.type==="wheel"){ctx.fillStyle="#17232e";rr(-16,-13,32,26,7);ctx.strokeStyle=t.c;for(let y=-8;y<=8;y+=8){ctx.beginPath();ctx.moveTo(-12,y);ctx.lineTo(12,y);ctx.stroke()}}else if(p.type==="shield"){ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(0,0,16,0,6.3);ctx.fill();ctx.stroke()}else{rr(-15,-15,30,30,4);if(["gun","rapid","rocket"].includes(p.type)){ctx.fillStyle="#dce9f5";ctx.fillRect(7,-4,p.type==="rocket"?25:22,8);if(p.type==="rapid"){ctx.fillRect(7,-9,18,4);ctx.fillRect(7,5,18,4)}}if(p.type==="core"){ctx.fillStyle="#fff";ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(8,0);ctx.lineTo(0,8);ctx.lineTo(-8,0);ctx.fill()}if(p.type==="repair"){ctx.fillStyle="#fff";ctx.fillRect(-3,-9,6,18);ctx.fillRect(-9,-3,18,6)}}ctx.restore();if(ratio<.55){ctx.fillStyle="#ff5b5b";ctx.fillRect(a.x-14,a.y+17,28*ratio,3)}}
function draw(){ctx.clearRect(0,0,W,H);ctx.strokeStyle="#173044";for(let xx=0;xx<W;xx+=S){ctx.beginPath();ctx.moveTo(xx,0);ctx.lineTo(xx,H);ctx.stroke()}for(let yy=0;yy<H;yy+=S){ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(W,yy);ctx.stroke()}if(!battle){tank.x=W/2;tank.y=H/2}parts.forEach(drawPart);for(let e of enemies){ctx.fillStyle=e.hit?"#fff":e.boss?"#c0264c":"#e14b4b";ctx.strokeStyle="#ff9a9a";ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,6.3);ctx.fill();ctx.stroke();ctx.fillStyle="#ff5577";ctx.fillRect(e.x-e.r,e.y-e.r-7,e.r*2*(e.hp/e.max),3);e.hit=Math.max(0,e.hit-1)}for(let s of shots){ctx.fillStyle=s.b?"#ffb020":"#eaf8ff";ctx.beginPath();ctx.arc(s.x,s.y,s.b?5:3,0,6.3);ctx.fill()}for(let p of particles){ctx.globalAlpha=Math.max(0,p.life/40);ctx.fillStyle=p.col;ctx.fillRect(p.x-2,p.y-2,4,4)}ctx.globalAlpha=1}
function loop(t){let dt=Math.min((t-last)/16.67||1,2);last=t;update(dt);draw();requestAnimationFrame(loop)}ui();requestAnimationFrame(loop);