const c=document.querySelector('#game'),x=c.getContext('2d'),arena=document.querySelector('#arena');let selected='core',parts=[],coins=0,battle=false,enemies=[],shots=[],last=0,hp=100;
const types={core:{color:'#38bdf8',hp:100},armor:{color:'#64748b',hp:70},gun:{color:'#f59e0b',hp:35},wheel:{color:'#22c55e',hp:45}};
function size(){c.width=arena.clientWidth*devicePixelRatio;c.height=arena.clientHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',size);size();
document.querySelectorAll('#shop button').forEach(b=>b.onclick=()=>{selected=b.dataset.part;document.querySelectorAll('#shop button').forEach(q=>q.classList.toggle('selected',q===b))});
function pos(e){let r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:p.clientX-r.left,y:p.clientY-r.top}}
c.addEventListener('pointerdown',e=>{if(battle)return;let p=pos(e),s=34,gx=Math.round((p.x-c.clientWidth/2)/s),gy=Math.round((p.y-c.clientHeight/2)/s);if(Math.abs(gx)>4||Math.abs(gy)>4)return;let old=parts.findIndex(a=>a.x===gx&&a.y===gy);if(old>=0)parts.splice(old,1);parts.push({x:gx,y:gy,type:selected,hp:types[selected].hp});draw()});
document.querySelector('#clear').onclick=()=>{if(!battle)parts=[]};
document.querySelector('#battle').onclick=()=>{if(battle){battle=false;enemies=[];shots=[];document.querySelector('#battle').textContent='⚔ BATTLE';document.querySelector('#mode').textContent='BUILD MODE';return}if(!parts.some(p=>p.type==='core')){msg('Place a CORE first!');return}battle=true;hp=100;document.querySelector('#hp').textContent=hp;document.querySelector('#battle').textContent='■ END BATTLE';document.querySelector('#mode').textContent='BATTLE MODE';msg('Defend the core!');spawn();requestAnimationFrame(loop)};
function msg(t){document.querySelector('#message').textContent=t}
function spawn(){if(!battle)return;let edge=Math.floor(Math.random()*4),w=c.clientWidth,h=c.clientHeight,p=edge<2?{x:Math.random()*w,y:edge?h:-20}:{x:edge===2?-20:w+20,y:Math.random()*h};enemies.push({...p,hp:3});setTimeout(spawn,900)}
function tankPart(p){let s=34,cx=c.clientWidth/2+p.x*s,cy=c.clientHeight/2+p.y*s;x.fillStyle=types[p.type].color;x.strokeStyle='#dbeafe';x.lineWidth=2;if(p.type==='wheel'){x.beginPath();x.arc(cx,cy,13,0,7);x.fill();x.stroke()}else{x.fillRect(cx-15,cy-15,30,30);x.strokeRect(cx-15,cy-15,30,30);if(p.type==='gun'){x.fillStyle='#e2e8f0';x.fillRect(cx+9,cy-4,23,8)}}}
function draw(){let w=c.clientWidth,h=c.clientHeight;x.clearRect(0,0,w,h);x.strokeStyle='#1d3040';x.lineWidth=1;for(let i=0;i<w;i+=34){x.beginPath();x.moveTo(i,0);x.lineTo(i,h);x.stroke()}for(let i=0;i<h;i+=34){x.beginPath();x.moveTo(0,i);x.lineTo(w,i);x.stroke()}parts.forEach(tankPart);enemies.forEach(e=>{x.fillStyle='#ef4444';x.beginPath();x.arc(e.x,e.y,13,0,7);x.fill()});shots.forEach(s=>{x.fillStyle='#f8fafc';x.beginPath();x.arc(s.x,s.y,4,0,7);x.fill()})}
function loop(t){if(!battle)return;let dt=Math.min((t-last)/16.67,2);last=t;let cx=c.clientWidth/2,cy=c.clientHeight/2;enemies.forEach(e=>{let a=Math.atan2(cy-e.y,cx-e.x);e.x+=Math.cos(a)*1.25*dt;e.y+=Math.sin(a)*1.25*dt;if(Math.hypot(e.x-cx,e.y-cy)<25){e.hp=0;hp=Math.max(0,hp-10);document.querySelector('#hp').textContent=hp}});enemies=enemies.filter(e=>e.hp>0);
if(parts.some(p=>p.type==='gun')&&enemies.length&&Math.floor(t/300)!==Math.floor((t-16)/300)){let e=enemies[0],a=Math.atan2(e.y-cy,e.x-cx);shots.push({x:cx,y:cy,vx:Math.cos(a)*8,vy:Math.sin(a)*8})}shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;enemies.forEach(e=>{if(Math.hypot(s.x-e.x,s.y-e.y)<16){e.hp--;s.dead=1;if(e.hp<=0){coins+=5;document.querySelector('#coins').textContent=coins}}})});shots=shots.filter(s=>!s.dead&&s.x>0&&s.y>0&&s.x<c.clientWidth&&s.y<c.clientHeight);enemies=enemies.filter(e=>e.hp>0);draw();if(hp<=0){battle=false;msg('CORE DESTROYED — rebuild and try again.');document.querySelector('#battle').textContent='⚔ BATTLE';document.querySelector('#mode').textContent='BUILD MODE';return}requestAnimationFrame(loop)}draw();